# Generated by Django 3.1.1 on 2021-03-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='piso',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='numero',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
