# Generated by Django 3.1.1 on 2021-03-12 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_auto_20210301_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('vencimiento', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='departamento',
            name='numero',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='piso',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='apellido',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='celular',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquilino', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cuentas.inquilino')),
                ('pagos', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cuentas.pagos')),
            ],
        ),
    ]
