# Generated by Django 3.1.1 on 2021-03-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_auto_20210316_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocuenta',
            name='estado',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
