# Generated by Django 3.1.1 on 2021-03-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_estadocuenta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocuenta',
            name='estado',
            field=models.CharField(choices=[('Al dia', 'Al dia'), ('Atrasado', 'Atrasado')], max_length=10, null=True),
        ),
    ]
