# Generated by Django 3.1.1 on 2021-03-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_auto_20210316_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='estadocuenta',
            name='fechaContrato_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='estadocuenta',
            name='fechaContrato_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='estadocuenta',
            name='proxVenc',
            field=models.DateField(null=True),
        ),
    ]
