# Generated by Django 3.1.1 on 2021-04-02 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0010_auto_20210331_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquilino',
            name='estadodecuenta',
        ),
        migrations.AddField(
            model_name='departamento',
            name='fechaContrato_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='fechaContrato_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='proxVenc',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pagos',
            name='inquilino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentas.inquilino'),
        ),
        migrations.DeleteModel(
            name='EstadoCuenta',
        ),
    ]
