# Generated by Django 3.1.1 on 2021-05-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0011_auto_20210402_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='fechaContrato_fin',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='fechaContrato_inicio',
        ),
        migrations.AddField(
            model_name='inquilino',
            name='fechaContrato_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='inquilino',
            name='fechaContrato_inicio',
            field=models.DateField(null=True),
        ),
    ]
