# Generated by Django 3.1.1 on 2021-12-29 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0012_auto_20210508_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='proxVenc',
        ),
        migrations.RemoveField(
            model_name='inquilino',
            name='fechaContrato_fin',
        ),
        migrations.RemoveField(
            model_name='inquilino',
            name='fechaContrato_inicio',
        ),
        migrations.AddField(
            model_name='pagos',
            name='concepto',
            field=models.CharField(default='Alquiler', max_length=20),
        ),
        migrations.AddField(
            model_name='pagos',
            name='nota',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('provincia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentas.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaContrato_inicio', models.DateField(null=True)),
                ('fechaContrato_fin', models.DateField(null=True)),
                ('fecha_vencimiento', models.DateField(null=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentas.departamento')),
                ('inquilino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentas.inquilino')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentas.localidad'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentas.provincia'),
        ),
    ]
