# Generated by Django 3.1.1 on 2021-12-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0013_auto_20211229_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='vencimiento',
        ),
        migrations.AddField(
            model_name='pagos',
            name='pago_mes',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
